### ISSUE TITLE
Driver responding with error code 400

### ISSUE THREAD

**Issue by BernhardFuchs** [evannetwork/evan-did-driver#4]
The `did:evan` driver on dev.uniresolver.io returns a status code 400 with follwing logs:
```
(node:47) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - "{\n  \"status\": \"error\",\n  \"error\": \"Given did (\\\"did:evan:EiBmZ7DieIHfwlphzl-encvM6MCw_jTQzqjyOfoTDeoq0w\\\") is no valid evan DID\"\n}"
    at new StatusCodeError (/usr/src/app/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
```

**Comment by S3bb1** [comment]
Thanks for reporting. How you got the DID?

I'll verify and update the driver.

**Comment by S3bb1** [comment]
Hi @BernhardFuchs,

i fixed the code and updated the latest image on docker hub. Issue should be now gone :)

**Comment by S3bb1** [comment]
seems the issue is solved, because uniresolver can resolve the did now :)
