### ISSUE TITLE
Example DID no resolvable

### ISSUE THREAD

**Issue by BernhardFuchs** [evannetwork/evan-did-driver#5]
When trying to resolve the example DID `did:evan:testcore:0x126E901F6F408f5E260d95c62E7c73D9B60fd734` the Resolver runs into a timeout. I'm not sure if there are related logs to the request inside the driver but I can see some errors e.g

```
(node:47) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - "{\n  \"status\": \"error\",\n  \"error\": \"Given did (\\\"did:evan:zkp:0x81c8457c65d61ecb6ad46703f8f3f4f6131315223c9834425bc8fc11e290f95a\\\") is no valid evan DID\"\n}"
    at new StatusCodeError (/usr/src/app/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
```

The resolver throws follwing `did:evan` related logs:
```
2022-05-16T17:08:39,683 WARN  [qtp423733503-50] u.w.s.ResolveServlet: Resolve problem for did:evan:zkp:0xd641c26161e769cef4b41760211972b274a8f37f135a34083e4e48b3f1035eda: Driver cannot retrieve resolve result for did:evan:zkp:0xd641c26161e769cef4b41760211972b274a8f37f135a34083e4e48b3f1035eda from http://evan-did-driver:8080/1.0/identifiers/did:evan:zkp:0xd641c26161e769cef4b41760211972b274a8f37f135a34083e4e48b3f1035eda: evan-did-driver:8080 failed to respond
uniresolver.ResolutionException: Driver cannot retrieve resolve result for did:evan:zkp:0xd641c26161e769cef4b41760211972b274a8f37f135a34083e4e48b3f1035eda from http://evan-did-driver:8080/1.0/identifiers/did:evan:zkp:0xd641c26161e769cef4b41760211972b274a8f37f135a34083e4e48b3f1035eda: evan-did-driver:8080 failed to respond
	at uniresolver.driver.http.HttpDriver.resolveRepresentation(HttpDriver.java:163)
	at uniresolver.local.LocalUniResolver.resolveOrResolveRepresentationWithDrivers(LocalUniResolver.java:167)
	at uniresolver.local.LocalUniResolver.resolveOrResolveRepresentation(LocalUniResolver.java:119)
	at uniresolver.local.LocalUniResolver.resolveRepresentation(LocalUniResolver.java:64)
	at uniresolver.web.WebUniResolver.resolveRepresentation(WebUniResolver.java:55)
	at uniresolver.web.servlet.ResolveServlet.doGet(ResolveServlet.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
```

Not sure if those logs are related to the issue with the test-did.

**Comment by S3bb1** [comment]
fixed in https://github.com/evannetwork/evan-did-driver/releases/tag/v0.1.2
